### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by EAWF** [EAWF/SiteDev-PHP2HTML#1]
- [ ] README.md
- [ ] Apply Credit to @Justin_Vincent
- [ ] Wiki Home Page
- [ ] Upload Donation QR Code and Display on Readme.md, and footer.
- [ ] Building the Raw HTML Template (HTML, Head, Nav, Body, Header, Article, Aside, Footer, Foot)
- [ ] Styling the Template
- [ ] Build Init.php
- [ ] 
- [ ]
